from framework.providers.apt import install_apt_packages

install_apt_packages("Shell Tools", [
    "autojump",
    "bat",
    "cmake",
    "cowsay",
    "curl",
    "fd-find",
    "fish",
    "fortune-mod",
    "fzf",
    "git",
    "git-lfs",
    "graphviz",
    "jq",
    "libxcb-xfixes0-dev",
    "lolcat",
    "neovim",
    "pkg-config",
    "ripgrep",
    "snapd",
    "xclip",
    "xsel",
    "yarnpkg",
    "zsh",
])
